parameters:
  database_driver: pdo_mysql
  database_host: 127.0.0.1
  database_port: null
  database_name: gallery
  database_user: gallery
  database_password: 5CjrHMmJWqYrFzay
  mailer_transport: smtp
  mailer_host: 127.0.0.1
  mailer_user: null
  mailer_password: null
  locale: en
  secret: 67046669d21bb510e2e432147850b84c2
  database_path: null
