parameters:
    sonata.admin.piece.class: DanFinnie\GalleryBundle\Admin\PieceAdmin

services:
    sonata.admin.piece:
        class: %sonata.admin.piece.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: pieces, label: "Piecez" }
        arguments:
            - ~
            - DanFinnie\GalleryBundle\Entity\Piece
            - 'SonataAdminBundle:CRUD'
        calls:
            - [ setTranslationDomain, [DanFinnieGalleryBundle]]