parameters:
#    dan_finnie_gallery.example.class: DanFinnie\GalleryBundle\Example

services:
#    dan_finnie_gallery.example:
#        class: %dan_finnie_gallery.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
