DanFinnie\GalleryBundle\Entity\Category:
    type: entity
    table: categories
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 255