DanFinnie\GalleryBundle\Entity\Piece:
    type: entity
    table: pieces
    oneToOne:
        picture:
            targetEntity: Application\Sonata\MediaBundle\Entity\Media
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 255
