parameters:
#    dan_finnie_site.example.class: DanFinnie\SiteBundle\Example

services:
    dan_finnie_site.navbar:
        class: '%mopa_bootstrap.navbar.generic%'
        scope: request
        arguments:
            - { leftmenu: @dan_finnie_site.navbar_main_menu=, rightmenu: @dan_finnie_site.navbar_right_menu= }
            - {}
            - { title: "dan_finnie_site", titleRoute: "dan_finnie_gallery_homepage", fixedTop: true, isFluid: false }
        tags:
            - { name: mopa_bootstrap.navbar, alias: frontendNavbar }

    dan_finnie_site.navbar_menu_builder:
        class: DanFinnie\SiteBundle\Menu\NavbarMenuBuilder
        scope: request
        arguments: [ '@knp_menu.factory', '@security.context' ]

    dan_finnie_site.navbar_main_menu:
        class: Knp\Menu\MenuItem
        factory_service: dan_finnie_site.navbar_menu_builder
        factory_method: createMainMenu
        arguments: [ '@request' ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }

    dan_finnie_site.navbar_right_menu:
        class: Knp\Menu\MenuItem
        factory_service: dan_finnie_site.navbar_menu_builder
        factory_method: createRightSideDropdownMenu
        arguments: [ '@request' ]
        scope: request
        tags:
            - { name: knp_menu.menu, alias: main }